### ISSUE TITLE
可不可以一行多列

### ISSUE THREAD

**Issue by hututu007** [chenquincy/vue-dynamic-form-component#37]
就是把两个input 框放在一行

**Comment by chenquincy** [comment]
@hututu007 可以添加全局 css 覆盖实现，给最外层的 form 添加 css
```css
.el-form.dynamic-form {
  display: flex;
  flex-wrap: wrap;
}
```
想要变更宽度的表单项添加
``` css
.el-form-item.dynamic-form-item {
 width: 50%;
}
```
后续版本会提供给 form-item 添加自定义类名的属性
